// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMO2YDnFl-ZgeWgRaJYvqX9TRzEjf4q0c',
    appId: '1:191932746274:android:8d1252c63b0be2b5',
    messagingSenderId: '191932746274',
    projectId: 'jcntvon',
    databaseURL: 'https://jcntvon.firebaseio.com',
    storageBucket: 'jcntvon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgCbShgOmC4htOoEX57tbcqF_M9VOIgYc',
    appId: '1:191932746274:ios:8d1252c63b0be2b5',
    messagingSenderId: '191932746274',
    projectId: 'jcntvon',
    databaseURL: 'https://jcntvon.firebaseio.com',
    storageBucket: 'jcntvon.appspot.com',
    iosClientId: '191932746274-k4shdrinpfs03egpo3jsvrrucrkd7a33.apps.googleusercontent.com',
    iosBundleId: 'kr.co.kodc.jcntv',
  );
}
